#!/bin/bash
set -euo pipefail

echo "=== Week 07 — IAM Identity Center SSO: Pre-deploy checklist ==="
echo ""
echo "This workspace (week-07-dev) is VCS-connected in HCP Terraform — HCP runs"
echo "plan/apply remotely from the GitHub repo, not from local terraform CLI."
echo ""
echo "Manual prerequisite (no Terraform resource exists for this step):"
echo "  IAM Identity Center must already be ENABLED for the organization."
echo "  AWS Console -> IAM Identity Center -> Enable -> choose 'Organization'"
echo "  instance type. Do this once, in the management account, before"
echo "  applying. There is no aws_ssoadmin resource to create the instance"
echo "  itself — only to manage permission sets/assignments once it exists."
echo ""
echo "Also confirm terraform.tfvars (or HCP workspace variables) sets real,"
echo "unique email addresses for every entry in var.users before applying —"
echo "Identity Center rejects duplicate or malformed emails."
echo ""
echo "Once both are done:"
echo "  1. git add -A && git commit && git push"
echo "  2. In the HCP UI: Start new plan on week-07-dev, then confirm Apply"
echo ""
echo "=== Checklist complete ==="
