#!/bin/bash
set -euo pipefail

echo "=== Week 09 — ECS Fargate Self-Service Cleanup ==="
echo ""
echo "This workspace (week-09-dev) is VCS-connected in HCP Terraform, so"
echo "'terraform destroy' from local CLI will fail the same way local 'apply'"
echo "does. Destroy must be confirmed from the HCP UI run page instead:"
echo "  HCP Terraform -> week-09-dev -> Actions -> Start new run -> Plan and"
echo "  apply (destroy)  -- or 'Queue destroy plan' under workspace settings."
echo ""
echo "Terraform only tracks the platform baseline (cluster, ALB, IAM, Lambda,"
echo "Step Functions, API Gateway, VPC). Every self-service ticket's ECR repo,"
echo "task definition, ECS service, target group, and listener rule were"
echo "created imperatively by fargate_provisioner via boto3 — they are NOT in"
echo "Terraform state and will NOT be removed by 'terraform destroy'."
echo ""
echo "Before destroying, delete any test services created via test_webhook.sh:"
echo "  aws ecs update-service --cluster <cluster> --service <svc> --desired-count 0"
echo "  aws ecs delete-service --cluster <cluster> --service <svc>"
echo "  aws ecr delete-repository --repository-name <repo> --force"
echo "Otherwise the shared ALB/cluster/VPC destroy will fail on dependent"
echo "target groups and ENIs still attached to a running service."
echo ""
read -rp "Press Enter once test services are cleaned up and you've confirmed the destroy run in the HCP UI (or Ctrl-C to abort): "
echo "=== Reminder acknowledged — go confirm the destroy run in HCP if you haven't ==="
