"""
Assemble Week 17's LinkedIn card HTML, inlining the official AWS icons.

    python scripts/build_week17_card.py
    python scripts/render_card.py week-17-mcp-platform-ops
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
ICONS = REPO / "scripts" / "assets" / "aws-icons"
OUT = REPO / "week-17-mcp-platform-ops" / "docs" / "linkedin" / "architecture-diagram.html"

WANT = {"lm": "lambda.svg", "ddb": "dynamodb.svg", "cw": "cloudwatch.svg"}


def symbols():
    out = []
    for key, fname in WANT.items():
        src = ICONS / fname
        if not src.exists():
            print("missing icon: %s" % src, file=sys.stderr)
            sys.exit(1)
        svg = src.read_text(encoding="utf-8")
        inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
        inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
        inner = re.sub(r'\sid="[^"]*"', "", inner)
        out.append('<symbol id="i-%s" viewBox="0 0 64 64">%s</symbol>' % (key, inner))
    return "\n".join(out)


HTML = """<!doctype html>
<!-- GENERATED by scripts/build_week17_card.py -- edit that, not this.
     Render:  python scripts/render_card.py week-17-mcp-platform-ops
     Authored at 1200x675 and shot at deviceScaleFactor 2. -->
<meta charset="utf-8">
<style>
  * { box-sizing: border-box }
  html, body { margin: 0; padding: 0 }
  body { width: 1200px; height: 675px; background: #fff; color: #16191f;
         font-family: "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
         -webkit-font-smoothing: antialiased; }
  .board { width: 1200px; height: 675px; padding: 26px 34px 22px; display: flex; flex-direction: column }
  .kicker { font-size: 13px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: #FF9900 }
  h1 { font-size: 31px; line-height: 1.15; font-weight: 600; margin: 8px 0 0; letter-spacing: -.015em }
  .sub { font-size: 13.5px; color: #5f6b7a; margin-top: 7px }
  .band { font-size: 11px; font-weight: 700; letter-spacing: .085em; text-transform: uppercase; color: #6c757d }
  code { font-family: "Cascadia Mono", Consolas, monospace; font-size: 11.5px;
         background: #f2f4f7; padding: 1px 4px; border-radius: 3px }
  .cols { display: flex; gap: 18px; margin-top: 14px; flex: 1 }
  .col { flex: 1; display: flex; flex-direction: column }
  .zone { border: 1px dashed #ccd3dc; border-radius: 9px; padding: 13px; margin-top: 6px;
          background: #fdfdfe; flex: 1; display: flex; flex-direction: column; justify-content: space-between }
  .node { border: 1px solid #dfe4ea; border-radius: 7px; background: #fff; padding: 10px 11px;
          display: flex; flex-direction: column; justify-content: center }
  .node + .node { margin-top: 8px }
  .node .n { font-size: 13.5px; font-weight: 600; display: flex; align-items: center; gap: 7px }
  .node .d { font-size: 12px; color: #6c757d; margin-top: 4px; line-height: 1.32 }
  .ico { width: 21px; height: 21px; flex: none }
  .meter { border: 1.6px solid #E7157B; background: #fff5fa }
  .meter .d { color: #b3125f }
  .free  { border: 1.4px solid #7AA116; background: #f8fcf5 }
  .cache { border: 2px solid #C925D1; background: #fdf6fe }
  .note { font-size: 11.5px; color: #6c757d; margin-top: 9px; line-height: 1.4 }
  .foot { margin-top: 12px; border-top: 1px solid #eceff2; padding-top: 11px;
          font-size: 12px; color: #5f6b7a; display: flex; gap: 26px }
  .foot b { color: #16191f }
</style>

<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>
__SYMBOLS__
</defs></svg>

<div class="board">
  <div class="kicker">AWS Platform Engineering Lab &middot; Week 17 of 52</div>
  <h1>I asked my AWS account what it was doing</h1>
  <div class="sub">Four days earlier the same question took eleven API calls &mdash; and a week of billing nobody noticed</div>

  <div class="cols">
    <div class="col">
      <div class="band">The server</div>
      <div class="zone">
        <div class="node">
          <div class="n">Lambda Function URL</div>
          <div class="d">AWS_IAM auth &middot; unsigned request gets 403 &middot; no idle cost</div>
        </div>
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-lm"/></svg>week17-mcp</div>
          <div class="d">Four read-only tools over MCP</div>
        </div>
        <div class="node cache">
          <div class="n"><svg class="ico"><use href="#i-ddb"/></svg>DynamoDB cache &middot; TTL 1 hour</div>
          <div class="d">A repeated cost question costs $0.00</div>
        </div>
        <div class="note">The role has no write on anything it reports on. A poisoned tool description can fill a cache; it cannot change the account.</div>
      </div>
    </div>

    <div class="col">
      <div class="band">What it reads</div>
      <div class="zone">
        <div class="node meter">
          <div class="n">Cost Explorer</div>
          <div class="d">$0.01 per request &mdash; the only metered read, and an LLM decides how often to call it</div>
        </div>
        <div class="node free">
          <div class="n">Resource Groups Tagging</div>
          <div class="d">What is running &middot; what has no owner &mdash; free</div>
        </div>
        <div class="node free">
          <div class="n"><svg class="ico"><use href="#i-cw"/></svg>CloudWatch</div>
          <div class="d">Alarm state &mdash; free</div>
        </div>
        <div class="note">Deployed by HCP Terraform: 7 managed resources, VCS-driven, OIDC credentials.</div>
      </div>
    </div>
  </div>

  <div class="foot">
    <div><b>Asked once:</b> &ldquo;what did I leave running with no owner?&rdquo; &rarr; 15 untagged resources</div>
    <div><b>Including</b> two buckets a teardown I had already signed off never saw</div>
  </div>
</div>
"""


def main():
    OUT.write_text(HTML.replace("__SYMBOLS__", symbols()), encoding="utf-8")
    print("wrote %s with %d official AWS icons" % (OUT.relative_to(REPO), len(WANT)))


if __name__ == "__main__":
    main()
