"""
Assemble Week 16's LinkedIn card HTML, inlining the official AWS icons.

Kept separate from render_card.py on purpose: this builds the self-contained
HTML (layout + icon symbols), render_card.py turns any such HTML into a PNG.
Re-run this if the icon set or the layout changes, then re-render.

    python scripts/build_week16_card.py
    python scripts/render_card.py week-16-devops-agent-investigations
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
ICONS = REPO / "scripts" / "assets" / "aws-icons"
OUT = REPO / "week-16-devops-agent-investigations" / "docs" / "linkedin" / "architecture-diagram.html"

# node id -> icon file. Only services with an official icon get one; anything
# else stays a plain labelled box rather than borrowing a lookalike.
WANTED = {
    "eb": "eventbridge.svg",
    "lm": "lambda.svg",
    "cw": "cloudwatch.svg",
    "ssm": "systems-manager.svg",
    "s3": "s3.svg",
    "ct": "cloudtrail.svg",
}


def symbols():
    out = []
    for key, fname in WANTED.items():
        src = ICONS / fname
        if not src.exists():
            print(f"missing icon: {src}", file=sys.stderr)
            sys.exit(1)
        svg = src.read_text(encoding="utf-8")
        inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
        inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
        # The icons carry duplicate element ids between files; stripping them
        # avoids an invalid document once six are inlined into one page.
        inner = re.sub(r'\sid="[^"]*"', "", inner)
        out.append(f'<symbol id="i-{key}" viewBox="0 0 64 64">{inner}</symbol>')
    return "\n".join(out)


HTML = """<!doctype html>
<!--
  GENERATED by scripts/build_week16_card.py -- edit that, not this.
  Render to PNG with:  python scripts/render_card.py week-16-devops-agent-investigations

  The board is exactly 1200x675 CSS pixels and is shot at deviceScaleFactor 2,
  so the PNG lands at 2400x1350 and stays crisp on a phone. Sharpness lives in
  the scale factor -- scaling this CSS up instead reflows every type metric.
-->
<meta charset="utf-8">
<style>
  * { box-sizing: border-box }
  html, body { margin: 0; padding: 0 }
  body {
    width: 1200px; height: 675px; background: #fff; color: #16191f;
    font-family: "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  .board { width: 1200px; height: 675px; padding: 24px 34px 22px; display: flex; flex-direction: column }

  .kicker { font-size: 13px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: #FF9900 }
  h1 { font-size: 31px; line-height: 1.15; font-weight: 600; margin: 8px 0 0; letter-spacing: -.015em }
  .sub { font-size: 13.5px; color: #5f6b7a; margin-top: 7px }

  .band { font-size: 11px; font-weight: 700; letter-spacing: .085em; text-transform: uppercase; color: #6c757d }

  .deploy { margin-top: 13px; border: 1px solid #e3e7ec; border-radius: 8px; padding: 10px 14px; background: #fcfcfd }
  .deploy b { font-size: 14px; font-weight: 600 }
  .deploy p { margin: 4px 0 0; font-size: 12px; color: #5f6b7a; line-height: 1.45 }
  code { font-family: "Cascadia Mono", Consolas, monospace; font-size: 11.5px; background: #f2f4f7; padding: 1px 4px; border-radius: 3px }

  /* .cols and .grader both grow, so the board fills top to bottom instead of
     stacking every spare pixel into one dead band above the footer. */
  .cols { display: flex; gap: 20px; margin-top: 12px; flex: 1.55 }
  .col { flex: 1; display: flex; flex-direction: column }
  .zone { border: 1px dashed #ccd3dc; border-radius: 9px; padding: 13px; margin-top: 6px; background: #fdfdfe;
          flex: 1; display: flex; flex-direction: column; justify-content: space-between }

  .row { display: flex; gap: 10px }
  .node { border: 1px solid #dfe4ea; border-radius: 7px; background: #fff; padding: 10px 11px; flex: 1;
          display: flex; flex-direction: column; justify-content: center }
  .node .n { font-size: 13.5px; font-weight: 600; line-height: 1.2; display: flex; align-items: center; gap: 7px }
  .node .d { font-size: 12px; color: #6c757d; margin-top: 4px; line-height: 1.33 }
  .node.hl { border: 2px solid #8C4FFF; padding: 9px 10px }
  .ico { width: 21px; height: 21px; flex: none }

  .note { font-size: 11px; color: #6c757d; margin-top: 8px; line-height: 1.4 }
  .break { margin-top: 9px; border: 1.5px solid #E7157B; border-radius: 6px; padding: 7px 10px;
           font-size: 12px; color: #b3125f; font-weight: 600; background: #fff5fa }

  .grader { margin-top: 13px; flex: 1; display: flex; flex-direction: column }
  .gcols { display: flex; gap: 10px; align-items: stretch; margin-top: 6px; flex: 1 }
  .claim { border: 2px solid #FF9900; border-radius: 7px; padding: 10px 12px; background: #fffaf2; flex: 1.3;
           display: flex; flex-direction: column; justify-content: center }
  .claim .n { font-size: 13.5px; font-weight: 600 }
  .claim .d { font-size: 12px; color: #5f6b7a; margin-top: 4px; line-height: 1.35 }
  .chev { align-self: center; color: #adb5bd; font-size: 16px }
  .foot { padding-top: 12px; font-size: 12px; color: #8a94a0 }
</style>

<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>
__SYMBOLS__
</defs></svg>

<div class="board">
  <div class="kicker">AWS Platform Engineering Lab &middot; Week 16 of 52</div>
  <h1>AWS DevOps Agent: the agent was right, and I still had to check</h1>
  <div class="sub">Break it in a known way &middot; write the answer down first &middot; grade the narrative against CloudTrail</div>

  <div class="deploy">
    <b>Deployed by HCP Terraform &mdash; VCS-driven workspace, OIDC dynamic credentials</b>
    <p>The <code>hashicorp/aws</code> provider has no DevOps Agent resources (issue #46894). Everything below is created through <code>awscc</code>, which generates from the CloudFormation registry.</p>
  </div>

  <div class="cols">
    <div class="col">
      <div class="band">The observed workload</div>
      <div class="zone">
        <div class="row">
          <div class="node"><div class="n"><svg class="ico"><use href="#i-eb"/></svg>EventBridge</div><div class="d">rate(5 minutes)</div></div>
          <div class="node"><div class="n"><svg class="ico"><use href="#i-lm"/></svg>Lambda</div><div class="d">order processor</div></div>
        </div>
        <div class="row" style="margin-top:8px">
          <div class="node"><div class="n"><svg class="ico"><use href="#i-ssm"/></svg>SSM Parameter</div><div class="d">processing-mode</div></div>
          <div class="node"><div class="n"><svg class="ico"><use href="#i-s3"/></svg>S3</div><div class="d">order records</div></div>
          <div class="node"><div class="n"><svg class="ico"><use href="#i-cw"/></svg>CloudWatch</div><div class="d">Errors, 300s</div></div>
        </div>
        <div class="break">The break &mdash; a human deletes the config-read inline policy. Code unchanged.</div>
      </div>
    </div>

    <div class="col">
      <div class="band">The agent &mdash; the agent space is the blast radius</div>
      <div class="zone">
        <div class="row">
          <div class="node"><div class="n">Operator App</div><div class="d">where a human asks</div></div>
          <div class="node"><div class="n">Association &mdash; AWS account</div><div class="d">account_type = "monitor" &middot; the only value</div></div>
        </div>
        <div class="row" style="margin-top:8px">
          <div class="node hl"><div class="n">AgentSpace</div><div class="d">week16-agent &middot; no budget or duration cap</div></div>
          <div class="node"><div class="n">Association &mdash; ServiceNow</div><div class="d">OAuth client_credentials &middot; no ticket produced</div></div>
        </div>
        <div class="note">Reads metrics, logs, config and CloudTrail. No actions-role property exists in the schema &mdash; the agent recommends, it never changes anything.</div>
      </div>
    </div>
  </div>

  <div class="grader">
    <div class="band">The grader &mdash; Week 15, already in this account</div>
    <div class="gcols">
      <div class="node"><div class="n"><svg class="ico"><use href="#i-ct"/></svg>CloudTrail</div><div class="d">organization trail &middot; DeleteRolePolicy: who, when, from where</div></div>
      <div class="chev">&#10230;</div>
      <div class="node"><div class="n">Ground truth, written FIRST</div><div class="d">stamped by break_it.sh before the agent is asked anything at all</div></div>
      <div class="chev">&#10230;</div>
      <div class="claim"><div class="n">The claim vs the fact</div><div class="d">An agent returns a narrative, and narratives persuade whether or not they are correct. Grade the conclusion; do not admire it.</div></div>
    </div>
  </div>

  <div class="foot">Two investigations, no hints, both correct &mdash; including one run with an innocent deployment landing 71 seconds before the real cause.</div>
</div>
"""


def main():
    OUT.write_text(HTML.replace("__SYMBOLS__", symbols()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} with {len(WANTED)} official AWS icons")


if __name__ == "__main__":
    main()
