"""Assemble Week 19's LinkedIn card HTML, inlining the official AWS icons.

    python scripts/build_week19_card.py
    python scripts/render_card.py week-19-gitops-argocd
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
ICONS = REPO / "scripts" / "assets" / "aws-icons"
OUT = REPO / "week-19-gitops-argocd" / "docs" / "linkedin" / "architecture-diagram.html"

WANT = {"eks": "eks.svg", "ec2": "ec2.svg"}


def symbols():
    out = []
    for key, fname in WANT.items():
        src = ICONS / fname
        if not src.exists():
            print("missing icon: %s" % src, file=sys.stderr)
            sys.exit(1)
        svg = src.read_text(encoding="utf-8")
        inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
        inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
        inner = re.sub(r'\sid="[^"]*"', "", inner)
        out.append('<symbol id="i-%s" viewBox="0 0 64 64">%s</symbol>' % (key, inner))
    return "\n".join(out)


HTML = """<!doctype html>
<!-- GENERATED by scripts/build_week19_card.py -- edit that, not this.
     Render:  python scripts/render_card.py week-19-gitops-argocd
     Authored at 1200x675 and shot at deviceScaleFactor 2. -->
<meta charset="utf-8">
<style>
  * { box-sizing: border-box }
  html, body { margin: 0; padding: 0 }
  body { width: 1200px; height: 675px; background: #fff; color: #16191f;
         font-family: "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
         -webkit-font-smoothing: antialiased; }
  .board { width: 1200px; height: 675px; padding: 26px 34px 20px; display: flex; flex-direction: column }
  .kicker { font-size: 13px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: #FF9900 }
  h1 { font-size: 32px; line-height: 1.14; font-weight: 600; margin: 8px 0 0; letter-spacing: -.015em }
  .sub { font-size: 13.5px; color: #5f6b7a; margin-top: 7px }
  .band { font-size: 10.5px; font-weight: 700; letter-spacing: .085em; text-transform: uppercase; color: #8a94a0 }
  .cols { display: flex; gap: 18px; margin-top: 15px; flex: 1 }
  .col { flex: 1; display: flex; flex-direction: column }
  .zone { border: 1px dashed #ccd3dc; border-radius: 9px; padding: 12px; margin-top: 6px;
          background: #fdfdfe; flex: 1; display: flex; flex-direction: column;
          justify-content: space-between }
  .node { border: 1px solid #dfe4ea; border-radius: 7px; background: #fff; padding: 9px 11px;
          display: flex; flex-direction: column; justify-content: center; flex: 1 }
  .node + .node { margin-top: 8px }
  .node .n { font-size: 13px; font-weight: 600; display: flex; align-items: center; gap: 7px }
  .node .d { font-size: 11.5px; color: #6c757d; margin-top: 3px; line-height: 1.3 }
  .ico { width: 20px; height: 20px; flex: none }
  .aws  { border: 1.6px solid #8C4FFF; background: #f8f5ff }
  .self { border: 1.6px solid #FF9900; background: #fff9f0 }
  .big { font-size: 20px; font-weight: 700 }
  .deny { margin-top: 14px; border: 1.5px solid #cc0c39; border-radius: 7px; background: #fff5f5;
          padding: 9px 12px }
  .deny .n { font-size: 13px; font-weight: 600; color: #cc0c39 }
  .deny .d { font-size: 11.5px; color: #6c757d; margin-top: 3px; line-height: 1.35 }
  .foot { margin-top: 12px; border-top: 1px solid #eceff2; padding-top: 10px;
          font-size: 12px; color: #5f6b7a }
  .foot b { color: #16191f }
</style>

<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>
__SYMBOLS__
</defs></svg>

<div class="board">
  <div class="kicker">AWS Platform Engineering Lab &middot; Week 19 of 52</div>
  <h1>Should you run Argo CD, or let AWS?</h1>
  <div class="sub">Same product, same Git repository, same cluster &mdash; and only one of them is actually in your cluster.</div>

  <div class="cols">
    <div class="col">
      <div class="band">Managed &middot; EKS Capability</div>
      <div class="zone">
        <div class="node aws">
          <div class="n">AWS runs the controllers</div>
          <div class="d">outside your cluster &middot; Identity Center is the only sign-in</div>
        </div>
        <div class="node">
          <div class="n"><span class="big">0</span> pods on your nodes</div>
          <div class="d">kubectl get pods -n argocd &rarr; No resources found</div>
        </div>
        <div class="node">
          <div class="n">$0.03 / hr</div>
          <div class="d">plus $0.0015 per Application-hour</div>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="band">Self-managed &middot; Helm</div>
      <div class="zone">
        <div class="node self">
          <div class="n">You run the controllers</div>
          <div class="d">every upstream feature &middot; any SSO you like</div>
        </div>
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-ec2"/></svg><span class="big">7</span> pods on your nodes</div>
          <div class="d">needs a node one size bigger to hold them</div>
        </div>
        <div class="node">
          <div class="n">+$0.0208 / hr</div>
          <div class="d">free software is not free to run</div>
        </div>
      </div>
    </div>
  </div>

  <div class="deny">
    <div class="n">They cannot both own the type definitions</div>
    <div class="d">The capability installs Argo CD's CRDs, and CRDs are cluster-scoped &mdash; so separate namespaces isolate the pods and isolate nothing about the CRDs. My first deploy failed on exactly that, and the error said <b>in namespace ""</b>.</div>
  </div>

  <div class="foot">
    <b>My drift test said the change never applied. It had &mdash; Argo CD reverted it in under three seconds</b> &mdash; when something exists to undo your change, watching for that change is a race you lose
  </div>
</div>
"""


def main():
    OUT.write_text(HTML.replace("__SYMBOLS__", symbols()), encoding="utf-8")
    print("wrote %s with %d official AWS icons" % (OUT.relative_to(REPO), len(WANT)))


if __name__ == "__main__":
    main()
