"""
Assemble Week 18's LinkedIn card HTML, inlining the official AWS icons.

    python scripts/build_week18_card.py
    python scripts/render_card.py week-18-eks-self-service
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
ICONS = REPO / "scripts" / "assets" / "aws-icons"
OUT = REPO / "week-18-eks-self-service" / "docs" / "linkedin" / "architecture-diagram.html"

WANT = {"eks": "eks.svg", "ec2": "ec2.svg", "far": "fargate.svg", "s3": "s3.svg"}


def symbols():
    out = []
    for key, fname in WANT.items():
        src = ICONS / fname
        if not src.exists():
            print("missing icon: %s" % src, file=sys.stderr)
            sys.exit(1)
        svg = src.read_text(encoding="utf-8")
        inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.S)
        inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
        inner = re.sub(r'\sid="[^"]*"', "", inner)
        out.append('<symbol id="i-%s" viewBox="0 0 64 64">%s</symbol>' % (key, inner))
    return "\n".join(out)


HTML = """<!doctype html>
<!-- GENERATED by scripts/build_week18_card.py -- edit that, not this.
     Render:  python scripts/render_card.py week-18-eks-self-service
     Authored at 1200x675 and shot at deviceScaleFactor 2. -->
<meta charset="utf-8">
<style>
  * { box-sizing: border-box }
  html, body { margin: 0; padding: 0 }
  body { width: 1200px; height: 675px; background: #fff; color: #16191f;
         font-family: "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
         -webkit-font-smoothing: antialiased; }
  .board { width: 1200px; height: 675px; padding: 26px 34px 20px; display: flex; flex-direction: column }
  .kicker { font-size: 13px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; color: #FF9900 }
  h1 { font-size: 32px; line-height: 1.14; font-weight: 600; margin: 8px 0 0; letter-spacing: -.015em }
  .sub { font-size: 13.5px; color: #5f6b7a; margin-top: 7px }
  .band { font-size: 10.5px; font-weight: 700; letter-spacing: .085em; text-transform: uppercase; color: #8a94a0 }
  .cols { display: flex; gap: 18px; margin-top: 15px; flex: 1 }
  .col { flex: 1; display: flex; flex-direction: column }
  /* space-between, not top-aligned. Three nodes in a tall panel otherwise
     leave a dead band under them, which reads as something missing. */
  .zone { border: 1px dashed #ccd3dc; border-radius: 9px; padding: 12px; margin-top: 6px;
          background: #fdfdfe; flex: 1; display: flex; flex-direction: column;
          justify-content: space-between }
  .node { border: 1px solid #dfe4ea; border-radius: 7px; background: #fff; padding: 9px 11px;
          display: flex; flex-direction: column; justify-content: center }
  .node { flex: 1; justify-content: center }
  .node + .node { margin-top: 8px }
  .node .n { font-size: 13px; font-weight: 600; display: flex; align-items: center; gap: 7px }
  .node .d { font-size: 11.5px; color: #6c757d; margin-top: 3px; line-height: 1.3 }
  .ico { width: 20px; height: 20px; flex: none }
  .rec  { border: 1.6px solid #8C4FFF; background: #f8f5ff }
  .only { border: 1.6px solid #FF9900; background: #fff9f0 }
  .deny { margin-top: 14px; border: 1.5px solid #cc0c39; border-radius: 7px; background: #fff5f5;
          padding: 9px 12px }
  .deny .n { font-size: 13px; font-weight: 600; color: #cc0c39 }
  .deny .d { font-size: 11.5px; color: #6c757d; margin-top: 3px; line-height: 1.35 }
  .foot { margin-top: 12px; border-top: 1px solid #eceff2; padding-top: 10px;
          font-size: 12px; color: #5f6b7a }
  .foot b { color: #16191f }
</style>

<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>
__SYMBOLS__
</defs></svg>

<div class="board">
  <div class="kicker">AWS Platform Engineering Lab &middot; Week 18 of 52</div>
  <h1>A namespace is not a boundary</h1>
  <div class="sub">It is a label. No CPU limit, no traffic blocking, no cloud permissions &mdash; every protection has to be added on purpose.</div>

  <div class="cols">
    <div class="col">
      <div class="band">Tenant A &middot; on EC2</div>
      <div class="zone">
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-ec2"/></svg>Managed node &middot; t3.small</div>
          <div class="d">exists only so the Pod Identity agent has a home</div>
        </div>
        <div class="node rec">
          <div class="n">Pod Identity</div>
          <div class="d">what AWS recommends &middot; no trust policy per cluster</div>
        </div>
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-s3"/></svg>its own bucket &mdash; and only that</div>
          <div class="d">ResourceQuota &middot; NetworkPolicy &middot; ServiceAccount</div>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="band">Tenant B &middot; on Fargate</div>
      <div class="zone">
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-far"/></svg>Fargate &middot; no node to manage</div>
          <div class="d">no DaemonSets, no privileged pods</div>
        </div>
        <div class="node only">
          <div class="n">IRSA</div>
          <div class="d">the only option here &middot; one OIDC provider per cluster</div>
        </div>
        <div class="node">
          <div class="n"><svg class="ico"><use href="#i-s3"/></svg>its own bucket &mdash; and only that</div>
          <div class="d">ResourceQuota &middot; NetworkPolicy &middot; ServiceAccount</div>
        </div>
      </div>
    </div>
  </div>

  <div class="deny">
    <div class="n">Two recommended defaults that cannot both be followed</div>
    <div class="d">Pod Identity is what AWS advises. Fargate means never managing a node. The Pod Identity agent is a privileged DaemonSet and Fargate runs neither &mdash; so the pod looks configured, times out, and reads as an IAM problem.</div>
  </div>

  <div class="foot">
    <b>My isolation test passed two of four checks against pods that never started</b> &mdash; the quota rejected them, and a check looking only for &ldquo;denied&rdquo; saw nothing, which scored as success
  </div>
</div>
"""


def main():
    OUT.write_text(HTML.replace("__SYMBOLS__", symbols()), encoding="utf-8")
    print("wrote %s with %d official AWS icons" % (OUT.relative_to(REPO), len(WANT)))


if __name__ == "__main__":
    main()
