#!/usr/bin/env python3
"""
generate_providers.py
---------------------
Generates providers.tf and main.tf for deploying EBSDashboardReadRole
into every member account in your AWS Organization via HCP Terraform.

Usage:
    # 1. Export account list from AWS Organizations
    aws organizations list-accounts \
        --query 'Accounts[?Status==`ACTIVE`].Id' \
        --output text | tr '\t' '\n' > accounts.txt

    # 2. Generate Terraform files
    python generate_providers.py \
        --accounts accounts.txt \
        --lambda-role arn:aws:iam::123456789012:role/yourorg-prod-lambda \
        --org-id o-ab1cd2ef34

    # 3. Commit generated files and push to HCP Terraform workspace

Why generated files instead of dynamic providers:
    Terraform does not support dynamic provider instantiation at runtime.
    Provider aliases must be declared statically. For 400 accounts this
    script generates the boilerplate so you don't write it by hand.
    Re-run whenever accounts are added or removed.
"""

import argparse
import os

parser = argparse.ArgumentParser(
    description="Generate Terraform providers.tf + main.tf for cross-account IAM role deployment"
)
parser.add_argument("--accounts",
                    required=True,
                    help="Path to file containing one AWS account ID per line")
parser.add_argument("--lambda-role",
                    required=True,
                    help="Full ARN of the Lambda role in the management account "
                         "(e.g. arn:aws:iam::123456789012:role/yourorg-prod-lambda)")
parser.add_argument("--org-id",
                    required=True,
                    help="AWS Organizations ID (e.g. o-ab1cd2ef34)")
parser.add_argument("--exec-role",
                    default="TerraformExecutionRole",
                    help="Name of the IAM role Terraform assumes in each member account. "
                         "Common values: TerraformExecutionRole, OrganizationAccountAccessRole, "
                         "AWSControlTowerExecution. Ask your platform team. (default: TerraformExecutionRole)")
parser.add_argument("--region",
                    default="us-east-1",
                    help="AWS region to deploy the IAM role in (default: us-east-1)")
parser.add_argument("--out-dir",
                    default=".",
                    help="Directory to write providers.tf and main.tf into (default: current dir)")
args = parser.parse_args()

# ── Load account IDs ──────────────────────────────────────────────────────────

with open(args.accounts) as f:
    accounts = [line.strip() for line in f if line.strip() and not line.startswith("#")]

print(f"Loaded {len(accounts)} accounts from {args.accounts}")

# Basic validation
for acct in accounts:
    if not acct.isdigit() or len(acct) != 12:
        raise ValueError(f"Invalid account ID: '{acct}' — must be 12 digits")

os.makedirs(args.out_dir, exist_ok=True)

# ── Write providers.tf ────────────────────────────────────────────────────────

providers_path = os.path.join(args.out_dir, "providers.tf")
with open(providers_path, "w") as f:
    f.write("# AUTO-GENERATED by generate_providers.py\n")
    f.write("# DO NOT EDIT MANUALLY — re-run the script to regenerate\n")
    f.write(f"# Accounts: {len(accounts)}  |  Exec role: {args.exec_role}\n\n")

    f.write('terraform {\n')
    f.write('  required_version = ">= 1.10.0"\n')
    f.write('  required_providers {\n')
    f.write('    aws = {\n')
    f.write('      source  = "hashicorp/aws"\n')
    f.write('      version = "~> 5.40"\n')
    f.write('    }\n')
    f.write('  }\n')
    f.write('}\n\n')

    f.write(f'variable "lambda_role_arn" {{\n')
    f.write(f'  description = "ARN of the Lambda role in the management account"\n')
    f.write(f'  default     = "{args.lambda_role}"\n')
    f.write(f'}}\n\n')

    f.write(f'variable "org_id" {{\n')
    f.write(f'  description = "AWS Organizations ID"\n')
    f.write(f'  default     = "{args.org_id}"\n')
    f.write(f'}}\n\n')

    for acct in accounts:
        f.write(f'provider "aws" {{\n')
        f.write(f'  alias  = "acc_{acct}"\n')
        f.write(f'  region = "{args.region}"\n')
        f.write(f'  assume_role {{\n')
        f.write(f'    role_arn = "arn:aws:iam::{acct}:role/{args.exec_role}"\n')
        f.write(f'  }}\n')
        f.write(f'}}\n\n')

print(f"  wrote {providers_path}")

# ── Write main.tf ─────────────────────────────────────────────────────────────

main_path = os.path.join(args.out_dir, "main.tf")
with open(main_path, "w") as f:
    f.write("# AUTO-GENERATED by generate_providers.py\n")
    f.write("# DO NOT EDIT MANUALLY — re-run the script to regenerate\n\n")

    for acct in accounts:
        f.write(f'module "ebs_role_{acct}" {{\n')
        f.write(f'  source          = "../modules/cross_account_role"\n')
        f.write(f'  lambda_role_arn = var.lambda_role_arn\n')
        f.write(f'  org_id          = var.org_id\n')
        f.write(f'  providers       = {{ aws = aws.acc_{acct} }}\n')
        f.write(f'}}\n\n')

print(f"  wrote {main_path}")
print(f"\nDone. Next steps:")
print(f"  1. Review the generated files")
print(f"  2. git add infra/cross_account_roles/ && git commit -m 'Generate cross-account role providers for {len(accounts)} accounts'")
print(f"  3. Push to your HCP Terraform workspace and run terraform apply")
