#!/bin/bash
set -euo pipefail

echo "=== Week 06 — Account Vending Machine Cleanup ==="
echo ""
echo "This workspace (week-06-dev) is VCS-connected in HCP Terraform, so"
echo "'terraform destroy' from local CLI will fail the same way local 'apply'"
echo "does. Destroy must be confirmed from the HCP UI run page instead:"
echo "  HCP Terraform -> week-06-dev -> Actions -> Start new run -> Plan and"
echo "  apply (destroy)  -- or 'Queue destroy plan' under workspace settings."
echo ""
echo "A destroy run removes the OUs, SCP, Lambda, Step Functions, and API"
echo "Gateway. It does NOT touch any AWS account that was actually vended"
echo "through this pipeline — those accounts are NOT in Terraform state."
echo ""
echo "AWS will refuse to delete a non-empty OU. If you vended any test accounts,"
echo "move them back to the Organization root (or close them) via the"
echo "Organizations console BEFORE destroying, or the organizations module"
echo "will fail to delete its OUs."
echo ""
echo "Closing a vended account is also not instant — closed accounts enter a"
echo "~90 day suspension window, they are not deleted immediately."
echo ""
read -rp "Press Enter once you've confirmed the destroy run in the HCP UI (or Ctrl-C to abort): "
echo "=== Reminder acknowledged — go confirm the destroy run in HCP if you haven't ==="
